[hty7.llemon.mediagen]
media_dir = "~/var/hty7/llemon/mediagen/media"
image_archive = "/srv/cloud/OpahSSD/pictures/ai/incoming"
video_archive = "/srv/cloud/OpahSSD/videos/ai/incoming"
input_files = [
    "AI images=/srv/cloud/OpahSSD/pictures/ai",
    "My Photos=/srv/cloud/OpahSSD/pictures/my-mac-photos/exports"
]

[qat.llemon.mediagen]
media_dir = "~/var/qat/llemon/mediagen/media"
image_archive = "/srv/ext/qat/pictures/ai/incoming"
video_archive = "/srv/ext/qat/videos/ai/incoming"
input_files = [
    "pictures=/srv/ext/qat/pictures"
]
