# Generated by Django 6.0.4 on 2026-05-09 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('priority', models.PositiveSmallIntegerField(help_text='1 is lowest priority, 5 is highest.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['due_date', '-priority', 'title'],
            },
        ),
    ]
