# Generated by Django 6.0.4 on 2026-05-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['finished', 'due_date', '-priority', 'title']},
        ),
        migrations.AddField(
            model_name='item',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='repeat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='repeat_from_due_date',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='repeat_interval',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
