# Generated by Django 6.0.4 on 2026-05-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0004_alter_category_options_category_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
